spring.application.name=backend
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=jdbc:sqlserver://localhost:62457;databaseName=hrms;integratedSecurity=false;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=12345678
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
jwt_secret=e0ffbf33ef1c8cecb9cd4bd1cfd36ec1b9eaebbf52ebf40902d7b330c467441341acf4865759b562fe3306a60d723e57100d6fb300a4f6a07307fa8ae338958b
spring.main.allow-circular-references=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
aws.s3.bucket-name=local-dev-bucket
aws.accessKeyId=local-dummy-access-key
aws.secretAccessKey=local-dummy-secret-key
aws.region=us-east-1
